
initial_state: 3

number_of_states: 4

transitionMatrix: [[0.9, 0.07, 0.02, 0.01],[0.04, 0.9, 0.04, 0.02],[0.02, 0.04, 0.9, 0.04], [0.01, 0.02, 0.07, 0.9]]

labels: # Possible classifications
  - Vessel

background_label: Background

confidenceThreshold: 0.2 # Confidence threshold used by the detector

states:
  0:
    name: terrible_performance
    bb_error_stats:
      mu_cx: -0.052
      sigma_cx: 3.615

      mu_cy: -0.890 # Expected value
      sigma_cy: 3.489 # Standard deviation

      mu_h: 0.140 # Expected value
      sigma_h: 7.178 # Standard deviation

      mu_w: -0.028 # Expected value
      sigma_w: 7.178 # Standard deviation
    confusion_matrix: # IMPORTANT! The values for the confusion matrix must be listed in the same order as the possible labels
      Vessel: 
        - 0.619
        - 0.381
      Background:
        - 1
        - null
    FDR: 0.255

  1:
    name: bad_performance
    bb_error_stats:
      mu_cx: -0.052
      sigma_cx: 3.615

      mu_cy: -0.890 # Expected value
      sigma_cy: 3.489 # Standard deviation

      mu_h: 0.140 # Expected value
      sigma_h: 7.178 # Standard deviation

      mu_w: -0.028 # Expected value
      sigma_w: 7.178 # Standard deviation
    confusion_matrix: # IMPORTANT! The values for the confusion matrix must be listed in the same order as the possible labels
      Vessel: 
        - 0.755
        - 0.245
      Background:
        - 1
        - null
    FDR: 0.115
  2:
    name: good_performance
    bb_error_stats:
      mu_cx: -0.052
      sigma_cx: 3.615

      mu_cy: -0.890 # Expected value
      sigma_cy: 3.489 # Standard deviation

      mu_h: 0.140 # Expected value
      sigma_h: 7.178 # Standard deviation

      mu_w: -0.028 # Expected value
      sigma_w: 7.178 # Standard deviation
    confusion_matrix: # IMPORTANT! The values for the confusion matrix must be listed in the same order as the possible labels
      Vessel: 
        - 0.849
        - 0.151
      Background:
        - 1
        - null
    FDR: 0.113
  3:
    name: excellent_performance
    bb_error_stats:
      mu_cx: -0.052
      sigma_cx: 3.615

      mu_cy: -0.890 # Expected value
      sigma_cy: 3.489 # Standard deviation

      mu_h: 0.140 # Expected value
      sigma_h: 7.178 # Standard deviation

      mu_w: -0.028 # Expected value
      sigma_w: 7.178 # Standard deviation
    confusion_matrix: # IMPORTANT! The values for the confusion matrix must be listed in the same order as the possible labels
      Vessel: 
        - 0.867
        - 0.133
      Background:
        - 1
        - null
    FDR: 0.089






