errorStats:
  sigma_cx: 30
  mu_cx: 0

  sigma_cy: 30 # Standard deviation
  mu_cy: 0 # Expected value

  sigma_h: 5 # Standard deviation
  mu_h: 0 # Expected value

  sigma_w: 5 # Standard deviation
  mu_w: 0 # Expected value

confusionMatrix:
  FN: 0.2
  FP: 0.2
  TP: 0.8
  TN: 0.8

labels: # Possible classifications
  - sailboat
  - motorboat
  - ferry

confusionMatrixLabels: # IMPORTANT! The values for the confusion matrix must be listed in the same order as the possible labels
  sailboat: 
    - 0.8
    - 0.1
    - 0.07
  motorboat:
    - 0.1
    - 0.85
    - 0.03
  ferry:
    - 0.02
    - 0.07
    - 0.9

confidenceThreshold: 0.34 # Confidence threshold used by the detector

falsePositivesLabels: # How often the background is classified as each of the labels
# IMPORTANT! The values for the false positives must be listed in the same order as the possible labels
# These must sum to 1, they mean: If there is a FP what is the probability for it to be of that class?
  - 0.5
  - 0.2
  - 0.3

transitionMatrix: [[0.2, 0.2, 0.2],[0.6, 0.6, 0.6],[0.2, 0.2, 0.2] ]

detectionConditions:
  precipitation: 0.0 # Includes  rain, snow, sleet, and hail
  fog: 0.9
  wind: 0
  darkness: 1 # Day, night, dusk, dawn

