
initial_state: 3

number_of_states: 4

transitionMatrix: [[0.7, 0.14, 0.02, 0.03],[0.2, 0.7, 0.14, 0.07],[0.07, 0.14, 0.7, 0.2], [0.03, 0.02, 0.14, 0.7]]

labels: # Possible classifications
  - Vessel

background_label: Background

confidenceThreshold: 0.2 # Confidence threshold used by the detector

states:
  0:
    name: terrible_performance
    bb_error_stats:
      mu_cx: 3
      sigma_cx: 42

      mu_cy: 8 # Expected value
      sigma_cy: 18 # Standard deviation

      mu_h: -24 # Expected value
      sigma_h: 72 # Standard deviation

      mu_w: -9 # Expected value
      sigma_w: 30 # Standard deviation
    confusion_matrix: # IMPORTANT! The values for the confusion matrix must be listed in the same order as the possible labels
      Vessel: 
        - 0.619
        - 0.381
      Background:
        - 1
        - null
    FDR: 0.255

  1:
    name: bad_performance
    bb_error_stats:
      mu_cx: 1
      sigma_cx: 33

      mu_cy: 4 # Expected value
      sigma_cy: 16 # Standard deviation

      mu_h: -4 # Expected value
      sigma_h: 58 # Standard deviation

      mu_w: -2 # Expected value
      sigma_w: 23 # Standard deviation
    confusion_matrix: # IMPORTANT! The values for the confusion matrix must be listed in the same order as the possible labels
      Vessel: 
        - 0.755
        - 0.245
      Background:
        - 1
        - null
    FDR: 0.115
  2:
    name: good_performance
    bb_error_stats:
      mu_cx: 0
      sigma_cx: 57

      mu_cy: 9 # Expected value
      sigma_cy: 22 # Standard deviation

      mu_h: -4 # Expected value
      sigma_h: 84 # Standard deviation

      mu_w: -4 # Expected value
      sigma_w: 35 # Standard deviation
    confusion_matrix: # IMPORTANT! The values for the confusion matrix must be listed in the same order as the possible labels
      Vessel: 
        - 0.849
        - 0.151
      Background:
        - 1
        - null
    FDR: 0.113
  3:
    name: excellent_performance
    bb_error_stats:
      mu_cx: 4
      sigma_cx: 48

      mu_cy: 7 # Expected value
      sigma_cy: 20 # Standard deviation

      mu_h: -8 # Expected value
      sigma_h: 73 # Standard deviation

      mu_w: -1 # Expected value
      sigma_w: 35 # Standard deviation
    confusion_matrix: # IMPORTANT! The values for the confusion matrix must be listed in the same order as the possible labels
      Vessel: 
        - 0.867
        - 0.133
      Background:
        - 1
        - null
    FDR: 0.089






