errorStats:
  sigma_cx: 30
  mu_cx: 0

  sigma_cy: 30 # Standard deviation
  mu_cy: 0 # Expected value

  sigma_h: 5 # Standard deviation
  mu_h: 0 # Expected value

  sigma_w: 5 # Standard deviation
  mu_w: 0 # Expected value

confusionMatrix:
  FN: 0.2
  FP: 0.2
  TP: 0.8
  TN: 0.8

labels: # Possible classifications
  - sailboat
  - motorboat
  - ferry

confusionMatrixLabels: # IMPORTANT! The values for the confusion matrix must be listed in the same order as the possible labels
  sailboat: 
    - 0.8
    - 0.19
    - 0.01
  motorboat:
    - 0.1
    - 0.85
    - 0.05
  ferry:
    - 0.09
    - 0.01
    - 0.9

confidenceThreshold: 0.34 #Confidence threshold used by the detector