
initial_state: 3

number_of_states: 4

transitionMatrix: [[0.99, 0.00475, 0.0005, 0.0005],
                   [0.0085, 0.99, 0.00475, 0.001],
                   [0.001, 0.00475, 0.99, 0.0085], 
                   [0.0005, 0.0005, 0.00475, 0.99]]


labels: # Possible classifications
  - Vessel

background_label: Background

confidenceThreshold: 0.2 # Confidence threshold used by the detector

states:
  0:
    name: terrible_performance
    bb_error_stats:
      error_covariance_matrix: [[1768, 167, 1796, -319], [167, 336, -594, -402], [1796, -594, 5172, 826], [-319, -402, 826, 888]]
      mean_error_vector: [4, 8, -24, -8]
    confusion_matrix: # IMPORTANT! The values for the confusion matrix must be listed in the same order as the possible labels
      Vessel: 
        - 0.619
        - 0.381
      Background:
        - 1
        - null
    FDR: 0.255

  1:
    name: bad_performance
    bb_error_stats:
      error_covariance_matrix: [[1407, 20, 349, -127], [20, 309, -315, -14], [349, -315, 3717, 104], [-127, -14, 104, 584]]
      mean_error_vector: [2, 5, -4, -1]
    confusion_matrix: # IMPORTANT! The values for the confusion matrix must be listed in the same order as the possible labels
      Vessel: 
        - 0.755
        - 0.245
      Background:
        - 1
        - null
    FDR: 0.115
  2:
    name: good_performance
    bb_error_stats:
      error_covariance_matrix: [[3328, 87, -301, -220], [87, 462, -254, -354], [-301, -254, 7296, 93], [-220, -354, 93, 1262]]
      mean_error_vector: [0, 8, -4, -4]
    confusion_matrix: # IMPORTANT! The values for the confusion matrix must be listed in the same order as the possible labels
      Vessel: 
        - 0.849
        - 0.151
      Background:
        - 1
        - null
    FDR: 0.113
  3:
    name: excellent_performance
    bb_error_stats:
      error_covariance_matrix: [[2354, 206, 1157, -169], [206, 390, -227, -389], [1157, -227, 5404, 115], [-169, -389, 115, 1223]]
      mean_error_vector: [4, 6, -8, 0]
    confusion_matrix: # IMPORTANT! The values for the confusion matrix must be listed in the same order as the possible labels
      Vessel: 
        - 0.867
        - 0.133
      Background:
        - 1
        - null
    FDR: 0.089






